package com.example.ai

import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Path
import retrofit2.http.Query
import java.util.concurrent.TimeUnit

interface GeminiApiService {
    @POST("v1beta/models/{model}:generateContent")
    suspend fun generateContent(
        @Path("model") model: String,
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

object GeminiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .client(okHttpClient)
        .addConverterFactory(MoshiConverterFactory.create(moshi))
        .build()

    val apiService: GeminiApiService = retrofit.create(GeminiApiService::class.java)

    const val INSTITUTIONAL_SYSTEM_PROMPT = """You are the Senior Institutional Gold (XAU/USD) Quantitative and Macro Analyst for the GOLD AI ANALYST terminal.
Responsibilities:
1. Provide institutional-grade technical analysis: trend alignment, key Support/Resistance, liquidity sweeps, Fair Value Gaps (FVG), RSI, MACD, and Bollinger Band momentum.
2. Integrate macroeconomic drivers: US Dollar Index (DXY), US 10-Year Real Yields, Fed rate expectations, CPI inflation, and Central Bank gold reserve demand.
3. Deliver actionable trade setups: Entry range, Stop-Loss invalidation, Take-Profit targets (TP1 & TP2), Risk/Reward ratio, and invalidation criteria.
4. Tone: Concise, rigorous, data-driven Wall Street quant. Avoid generic fluff."""

    suspend fun analyzeGoldMarket(
        apiKey: String,
        prompt: String,
        conversationHistory: List<Pair<String, String>>, // role to message
        useHighThinking: Boolean,
        marketContext: String
    ): Result<String> = withContext(Dispatchers.IO) {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext Result.failure(
                IllegalStateException("Gemini API key is not configured. Please add your key in the Settings tab or configure the Secrets panel.")
            )
        }

        // Model selection rule: gemini-3.1-pro-preview for High Thinking, gemini-3.5-flash for general
        val model = if (useHighThinking) "gemini-3.1-pro-preview" else "gemini-3.5-flash"

        val contents = mutableListOf<ContentItem>()
        for ((role, text) in conversationHistory) {
            val apiRole = if (role.equals("user", ignoreCase = true)) "user" else "model"
            contents.add(ContentItem(role = apiRole, parts = listOf(PartItem(text = text))))
        }

        val enrichedPrompt = "$marketContext\n\nUser Question:\n$prompt"
        contents.add(ContentItem(role = "user", parts = listOf(PartItem(text = enrichedPrompt))))

        val genConfig = if (useHighThinking) {
            GenerationConfig(
                temperature = 0.3f,
                topP = 0.95f,
                thinkingConfig = ThinkingConfig(thinkingLevel = "high") // ThinkingLevel.HIGH
            )
        } else {
            GenerationConfig(temperature = 0.5f, topP = 0.95f)
        }

        val request = GeminiRequest(
            contents = contents,
            systemInstruction = ContentItem(parts = listOf(PartItem(text = INSTITUTIONAL_SYSTEM_PROMPT))),
            generationConfig = genConfig
        )

        try {
            val response = apiService.generateContent(model = model, apiKey = apiKey, request = request)
            val candidateText = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
            if (!candidateText.isNullOrBlank()) {
                Result.success(candidateText)
            } else if (response.error != null) {
                Result.failure(Exception("Gemini error (${response.error.code}): ${response.error.message}"))
            } else {
                Result.failure(Exception("No analysis generated by model."))
            }
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
